language: cpp

matrix:
  include:
    - os: linux
      dist: xenial
      addons:
        apt:
          packages:
            - libgtest-dev
    - os: osx

compiler:
  - clang
  - gcc

script:
  - mkdir build
  - cd build
  - cmake ..
  - make
  - make test