language: cpp

matrix:
  include:
    - os: linux
      dist: xenial
    - os: osx

compiler:
  - clang
  - gcc

before_install:
  - git clone http://github.com/google/googletest.git
  - cd googletest
  - cmake .
  - make
  - sudo make install
  - cd -

script:
  - mkdir build
  - cd build
  - cmake ..
  - make
  - make test