language: cpp

matrix:
  include:
    - os: linux
      dist: xenial
    - os: osx

addons:
  apt:
    packages:
      - libgtest-dev

compiler:
  - clang
  - gcc

script:
  - mkdir build
  - cd build
  - cmake ..
  - make
  - make test