language: cpp

os: linux
dist: xenial

compiler:
  - clang
  - gcc

before_install:
  - git clone http://github.com/google/googletest.git
  - cd googletest
  - cmake .
  - make
  - sudo make install

script:
  - mkdir build
  - cd build
  - cmake ..
  - make
  - make test