language: cpp

matrix:
  include:
    - os: linux
      dist: xenial
    - before_install:
        - sudo apt install libgtest-dev
    - os: osx

compiler:
  - clang
  - gcc

script:
  - mkdir build
  - cd build
  - cmake ..
  - make
  - make test